name: flame_game
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flame: 1.10.0
  cupertino_icons: ^1.0.2
  flame_tiled: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/Terrain/
      - assets/tiles/